#if !canImport(ObjectiveC)
import XCTest

extension PolkadotTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PolkadotTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PolkadotTests.__allTests__PolkadotTests),
    ]
}
#endif
