#if !canImport(ObjectiveC)
import XCTest

extension HashersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HashersTests = [
        ("testBlake2b128", testBlake2b128),
        ("testBlake2b128Concat", testBlake2b128Concat),
        ("testBlake2b256", testBlake2b256),
        ("testBlake2b512", testBlake2b512),
    ]
}

extension StorageKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageKeyTests = [
        ("testDoubleMapEncodind", testDoubleMapEncodind),
    ]
}

extension TypeParsingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypeParsingTests = [
        ("testCompoundType", testCompoundType),
        ("testDoNotConstructParsing", testDoNotConstructParsing),
        ("testFixedArrayParcing", testFixedArrayParcing),
        ("testMapParsing", testMapParsing),
        ("testNestedFixedArrayParcing", testNestedFixedArrayParcing),
        ("testNestedSliceParcing", testNestedSliceParcing),
        ("testNestedTupleParsing", testNestedTupleParsing),
        ("testResultParsing", testResultParsing),
        ("testSliceParcing", testSliceParcing),
        ("testTupleParsing", testTupleParsing),
        ("testVectorParsing", testVectorParsing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HashersTests.__allTests__HashersTests),
        testCase(StorageKeyTests.__allTests__StorageKeyTests),
        testCase(TypeParsingTests.__allTests__TypeParsingTests),
    ]
}
#endif
