#if !canImport(ObjectiveC)
import XCTest

extension HashersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HashersTests = [
        ("testBlake2b128", testBlake2b128),
        ("testBlake2b128Concat", testBlake2b128Concat),
    ]
}

extension StorageKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageKeyTests = [
        ("testDoubleMapEncodind", testDoubleMapEncodind),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HashersTests.__allTests__HashersTests),
        testCase(StorageKeyTests.__allTests__StorageKeyTests),
    ]
}
#endif
