#if !canImport(ObjectiveC)
import XCTest

extension SubstrateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubstrateTests = [
        ("testMetadataParsing", testMetadataParsing),
        ("testStorageCall", testStorageCall),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SubstrateTests.__allTests__SubstrateTests),
    ]
}
#endif
