#if !canImport(ObjectiveC)
import XCTest

extension WebSocketClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__WebSocketClientTests = [
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(WebSocketClientTests.__allTests__WebSocketClientTests),
    ]
}
#endif
